package app;

import javax.swing.*;
import java.awt.Color;
import java.util.ArrayList;

public class TestAutoComplete extends JFrame {


    /*
     * To change this license header, choose License Headers in Project Properties.
     * To change this template file, choose Tools | Templates
     * and open the template in the editor.
     */




    /**
     *
     * @author RAVEN
     */


        /**
         * Creates new form Main
         */
        public TestAutoComplete() {
            initComponents();
            getContentPane().setBackground(new Color(255, 255, 255));
            String suggestions = "[LOVE DIVE, lovely (with Khalid), OMG, GODS, " +
                    "SUMMER TIME SADNESS HARDSTYLE, Super Shy, What's Up Danger (with Black Caviar), " +
                    "Kitsch, Enemy (with JID) - from the series Arcane League of Legends, " +
                    "PART OF ME HARDSTYLE (SPED UP), New Jeans, Either Way, Phoenix, Ditto, " +
                    "Blue Blood, EVERYTIME WE TOUCH HARDSTYLE (SPED UP), Playground (from the series Arcane League of Legends), " +
                    "I AM, I WANT, golden hour, Legends Never Die, OUTSIDE HARDSTYLE SPED UP, WAVE, " +
                    "Cool With You, PART OF ME HARDSTYLE, Enemy - From the series Arcane League of Legends, " +
                    "Warriors, RISE, ETA, Maria, Lips, Hype Boy, SET FIRE TO THE RAIN HARDSTYLE, Way Up, " +
                    "OUTSIDE HARDSTYLE, 섬찟 (Hypnosis), MIDDLE OF THE NIGHT - HARDSTYLE REMIX, Queencard, VILLAIN, " +
                    "ELEVEN, Attention, Get Up, DRUM GO DUM, JUST DANCE HARDSTYLE, Cupid - Twin Ver., NOT YOUR GIRL, " +
                    "你的答案, ONLY GIRL HARDSTYLE, Take Over, DARK HORSE HARDSTYLE]";
            String[] elements = suggestions.substring(1, suggestions.length() - 1).split(", ");

            for (String element : elements) {
                System.out.println(element);
                txt.addItemSuggestion(element);
            }
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

            jButton1 = new javax.swing.JButton();
            txt = new TextFieldSuggestion();
            textFieldSuggestion3 = new TextFieldSuggestion();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            jButton1.setText("jButton1");

            txt.setText("textFieldSuggestion2");

            textFieldSuggestion3.setText("textFieldSuggestion2");
            textFieldSuggestion3.setRound(0);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap(614, Short.MAX_VALUE)
                                    .addComponent(jButton1)
                                    .addGap(211, 211, 211))
                            .addGroup(layout.createSequentialGroup()
                                    .addGap(177, 177, 177)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textFieldSuggestion3, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                    .addGap(131, 131, 131)
                                    .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(textFieldSuggestion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(194, 194, 194)
                                    .addComponent(jButton1)
                                    .addContainerGap(43, Short.MAX_VALUE))
            );

            pack();
            setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
             */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(TestAutoComplete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(TestAutoComplete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(TestAutoComplete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(TestAutoComplete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            /* Create and display the form */

            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new TestAutoComplete().setVisible(true);
                }
            });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButton1;
        private TextFieldSuggestion textFieldSuggestion3;
        private TextFieldSuggestion txt;
        // End of variables declaration//GEN-END:variables
    }


